language: node_js
node_js:
- '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
deploy:
  provider: heroku
  app: ti-02-instagram
  api_key:
    secure: ehzfE8cBk7ObGv2/wN9m0Tfz1YvLWUCHGRWApYUkT/sK0X/nGHNaIuZLm1QDFrMuqxCLGPEnq3V+xbU8pvzpriEfgxL7v7EBcJwiNtVtWI4ZeNk2CcTj19tD5aM9AgKMM8riGzUgL8du9dzys+fPQpaMlmp7XX/fFoy3m8kzOhvRudcEDuYOPsMUFbutaNUiJnksDDzQms+G6nQJwpBnO44GIeLwsJomf55vntQHi+2nPBKzgQfz7nkowuvLtVjA4jOJbS4PKK7VGNokXAbxFH6t38OgHj+gI6Y+v3YDPbGctO0hQD+XyYiCzRuWk9N7zH7pLhw2PBkKiFf5T8XBqRHPU9hwnIXTzEXbtfYBFGFTM3XQO3VgFFgYrKZTVM8S7JC9gCkWAmsVZ1WDz2CPPxVFgb02JEFa3l3ua0dja2YYx7o0PEX5qv0DJr1BXGlfk57XVzx2sqgmEtL4P/9SmQbNMOqTZlzDpL52RT1P6Vr1AFTMFP6M7kK0RW+ULbDMhhHxI6fxudovB05fFUC6LpDEh796pOqiuIOE+nycVVZbON/5oeP84h/+EQtlYmN15YjQnAPRToBf4NKoEFVMuHpGxbq8AcwNaKg3HpsJyEROX7gZP+bGvkovX2CiQbPX2ST6qViOXLAD353+h1WJHPFcJdIbVW5fKsTg7+jzvIE=
